export const GET_EMAILS_LIST_INITIATED = 'GET_EMAILS_LIST_INITIATED'
export const GET_EMAILS_LIST_SUCCESS = 'GET_EMAILS_LIST_SUCCESS'
export const GET_EMAILS_LIST_FAIL = 'GET_EMAILS_LIST_FAIL'
export const REST_GET_EMAILS_LIST = 'REST_GET_EMAILS_LIST'

export const PAGE_CHANGE = 'PAGE_CHANGE'
export const SELECT_CHANGE = 'SELECT_CHANGE'

export const SEARCH_EMAIL_LIST_INITIATED = 'SEARCH_EMAIL_LIST_INITIATED'
export const SEARCH_EMAIL_LIST_SUCCESS = 'SEARCH_EMAIL_LIST_SUCCESS'
export const SEARCH_EMAIL_LIST_FAILED = 'SEARCH_EMAIL_LIST_FAILED'
export const RESET_EMAILS_SEARCH = 'RESET_EMAILS_SEARCH'

export const CLEAR_MAILS_DATA_INITIATED = 'CLEAR_MAILS_DATA_INITIATED'
export const CLEAR_MAILS_DATA_SUCCESS = 'CLEAR_MAILS_DATA_SUCCESS'
export const CLEAR_MAILS_DATA_FAILED = 'CLEAR_MAILS_DATA_FAILED'
export const RESET_CLEAR_MAILS_DATA = 'RESET_CLEAR_MAILS_DATA'

export const DELETE_EMAILS_POST_API_INITIATED = 'DELETE_EMAILS_POST_API_INITIATED'
export const DELETE_EMAILS_POST_API_SUCCESS = 'DELETE_EMAILS_POST_API_SUCCESS'
export const DELETE_EMAILS_POST_API_FAILED = 'DELETE_EMAILS_POST_API_FAILED'
export const RESET_DELETE_EMAILS_POST_API = 'RESET_DELETE_EMAILS_POST_API'

export const GET_ATTACHMENT_INITIATED = 'GET_ATTACHMENT_INITIATED'
export const GET_ATTACHMENT_SUCCESS = 'GET_ATTACHMENT_SUCCESS'
export const GET_ATTACHMENT_FAILED = 'GET_ATTACHMENT_FAILED'
export const RESET_ATTACHMENT = 'RESET_ATTACHMENT'
