export const LOGIN_INITIATED = 'LOGIN_INITIATED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const LOGOUT_SUCCESSFUL = 'LOGOUT_SUCCESSFUL'

export const FETCH_PROFILE_INITIATED = 'FETCH_PROFILE_INITIATED'
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS'
export const FETCH_PROFILE_FAILED = 'FETCH_PROFILE_FAILED'

export const UPDATE_PROFILE_INITIATED = 'UPDATE_PROFILE_INITIATED'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED'
export const RESET_PROFILE_UPDATE_STATE = 'RESET_PROFILE_UPDATE_STATE'

export const UPDATE_ADMIN_PASSWORD_INITIATED = 'UPDATE_ADMIN_PASSWORD_INITIATED'
export const UPDATE_ADMIN_PASSWORD_SUCCESS = 'UPDATE_ADMIN_PASSWORD_SUCCESS'
export const UPDATE_ADMIN_PASSWORD_FAILED = 'UPDATE_ADMIN_PASSWORD_FAILED'
export const RESET_ADMIN_PASSWORD_UPDATE_STATE = 'RESET_ADMIN_PASSWORD_UPDATE_STATE'
